server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderservice #eureka的服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos的服务地址
    sentinel:
      transport:
        dashboard: localhost:8098 #sentinel服务地址
  main:
    allow-circular-references: true
#eureka:
#  client:
#    service-url: #eureka的地址信息
#      defaultZone: http://localhost:10086/eureka
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 制定饥饿加载的服务名称
      - userservice
feign:
  sentinel:
    enabled: true # 开启feign对sentinel的支持